- name: Copy background wallpaper
  ansible.builtin.copy:
    src: "{{ bench_repo_root }}/images/{{bench_wallpaper_src_jxl}}"
    dest: "{{ bench_wallpaper_system_path }}/default.jxl"
    mode: '0644'
  become: true

- name: Copy background wallpaper
  ansible.builtin.copy:
    src: "{{ bench_repo_root }}/images/{{bench_wallpaper_src_jxl}}"
    dest: "{{ bench_wallpaper_system_path }}/images/default.jxl"
    mode: '0644'
  become: true

# --- Desktop background (pcmanfm, for user) ---
- name: Create pcmanfn configuration dir
  ansible.builtin.file:
    path: "/home/{{item }}/.config/pcmanfm/LXDE"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0755'
  loop: "{{bench_users}}"

- name: Imposta lo sfondo del desktop nel file di configurazione
  ansible.builtin.copy:
    dest: "/home/{{ item }}/.config/pcmanfm/LXDE/desktop-items-0.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    content: |
      [*]
      wallpaper_mode=crop
      wallpaper=/usr/share/backgrounds/images/default.jxl
      desktop_bg=#000000
      desktop_fg=#ffffff
      desktop_shadow=#000000
      show_wm_menu=0
      sort=mtime;ascending;
      show_documents=0
      show_trash=1
      show_mounts=0
  loop: "{{bench_users}}"
