---
bench_repo_root: "{{ playbook_dir | dirname | dirname }}"

bench_shell_users:
  - develer
  - collaudo

bench_base_packages:
  - openssl
  - git
  - git-lfs
  - direnv
  - tmux
  - python3.10
  - python3.10-devel
  - gcc

bench_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

bench_docker_users:
  - develer
  - collaudo

bench_develer_user: develer
bench_collaudo_user: collaudo

insync_gpg_key_url: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
insync_repo_baseurl: "http://yum.insync.io/fedora/{{ ansible_distribution_major_version }}/"
